### ISSUE TITLE
example from docs does not work

### ISSUE THREAD

**Issue by drbenvincent** [erdogant/bnlearn#6]
Hello. I am just trying out this package, but I find an error when I run an example from the docs.

All the below code works
```python
import bnlearn
from pgmpy.factors.discrete import TabularCPD

# Define the network structure
edges = [('Cloudy', 'Sprinkler'),
         ('Cloudy', 'Rain'),
         ('Sprinkler', 'Wet_Grass'),
         ('Rain', 'Wet_Grass')]

# Make the actual Bayesian DAG
DAG = bnlearn.make_DAG(edges)

bnlearn.plot(DAG)

cpt_cloudy = TabularCPD(variable='Cloudy', variable_card=2, values=[[0.5], [0.5]])

cpt_sprinkler = TabularCPD(variable='Sprinkler', variable_card=2,
                           values=[[0.5, 0.9],
                                   [0.5, 0.1]],
                           evidence=['Cloudy'], evidence_card=[2])
# Rain
cpt_rain = TabularCPD(variable='Rain', variable_card=2,
                      values=[[0.8, 0.2],
                              [0.2, 0.8]],
                      evidence=['Cloudy'], evidence_card=[2])

# Wet Grass
cpt_wet_grass = TabularCPD(variable='Wet_Grass', variable_card=2,
                           values=[[1, 0.1, 0.1, 0.01],
                                   [0, 0.9, 0.9, 0.99]],
                           evidence=['Sprinkler', 'Rain'],
                           evidence_card=[2, 2])

DAG = bnlearn.make_DAG(DAG, CPD=[cpt_cloudy, cpt_sprinkler, cpt_rain, cpt_wet_grass])

DAG = bnlearn.print_CPD(DAG)
```

But I get the following error when trying to run inference
```python
q1 = bnlearn.inference.fit(DAG, variables=['Wet_Grass'], evidence={'Rain':1, 'Sprinkler':0, 'Cloudy':1})
```

Error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-6649bfc3c510> in <module>
----> 1 q1 = bnlearn.inference.fit(DAG, variables=['Wet_Grass'], evidence={'Rain':1, 'Sprinkler':0, 'Cloudy':1})

/anaconda3/lib/python3.7/site-packages/bnlearn/inference.py in fit(model, variables, evidence, verbose)
     60     """
     61     if verbose>=3: print('[BNLEARN][inference] Variable Elimination..')
---> 62     adjmat = model['adjmat']
     63 
     64     if not np.all(np.isin(variables, adjmat.columns)):

TypeError: 'NoneType' object is not subscriptable
```

**Comment by erdogant** [comment]
Dear vincent,

Thank you for using bnlearn and mailing me about this issue!
I fixed the bug. Can you pip install again?
pip install -U bnlearn

Op zo 24 mei 2020 om 16:50 schreef Benjamin T. Vincent <
notifications@github.com>:

**Comment by drbenvincent** [comment]
Thanks for your quick response. I've updated with pip as you say, and I still get the same error unfortunately. As far as I can tell I have the latest version (0.3.4). Typing `bn.version` gives me

     <module 'packaging.version' from '/anaconda3/lib/python3.7/site-packages/packaging/version.py'>

but no version number. But typing `conda list` confirms version 0.3.4

**Comment by erdogant** [comment]
Mm... Exactly the same error? Did you also try to restart your kernel?

The version can be checked by bnlear.__version__

Verstuurd vanaf mijn iPhone

**Comment by drbenvincent** [comment]
Yes, restarted everything, and also confirmed 0.3.4 using `bnlearn.__version__`

Error is

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-6649bfc3c510> in <module>
----> 1 q1 = bnlearn.inference.fit(DAG, variables=['Wet_Grass'], evidence={'Rain':1, 'Sprinkler':0, 'Cloudy':1})

/anaconda3/lib/python3.7/site-packages/bnlearn/inference.py in fit(model, variables, evidence, verbose)
     59     """
     60     if verbose>=3: print('[BNLEARN][inference] Variable Elimination..')
---> 61     adjmat = model['adjmat']
     62 
     63     if not np.all(np.isin(variables, adjmat.columns)):

TypeError: 'NoneType' object is not subscriptable
```

**Comment by erdogant** [comment]
I see,

There was an issue in the example. Its fixed now.
Printing the CPD should not overwrite the DAG.
I created an update in bnlearn to catch the error.

bnlearn.print_CPD(DAG)



Op ma 25 mei 2020 om 17:54 schreef Benjamin T. Vincent <
notifications@github.com>:

**Comment by drbenvincent** [comment]
Thanks for the update. Yes, that works if I change from this
```python
DAG = bnlearn.print_CPD(DAG)
```

to this

```python
bnlearn.print_CPD(DAG)
```
