### ISSUE TITLE
import issue, version compatibility

### ISSUE THREAD

**Issue by MenigStar91** [erdogant/bnlearn#86]
The current code of bnlearn is not compatible with the latest numpy version.
Could we have it updated or contribute?

**Comment by erdogant** [comment]
I could not reproduce an error using numpy. Can you show by example how it occurs to you? A contributing would be great 👍🏻

**Comment by MenigStar91** [comment]
While there shows no error in pip install bnlearn, import bnlearn returns some issue when using with the latest version of numpy. 
![image](https://github.com/erdogant/bnlearn/assets/76737246/926d6522-bce4-45f2-9741-0112b54ec07e)
![image](https://github.com/erdogant/bnlearn/assets/76737246/574fe8df-48d3-4d2a-9c39-0675d7e59557)
Similar issue happens if we try importing of desktop.

**Comment by erdogant** [comment]
Can you also try to install it from pypi?
`pip install -U bnlearn
`

**Comment by MenigStar91** [comment]
its the same issue, whichever of the 3ways we use to install it.

**Comment by erdogant** [comment]
I was able to reproduce the error. In my case it was fixed when updating to the correct numpy version. 
![fix_bug_numpy_error_bnlearn](https://github.com/erdogant/bnlearn/assets/31008129/3a8102b4-a150-4468-bb67-8670d2782fc2)

**Comment by vin2015-edem** [comment]
Thanks @erdogant  for the advice, but unfortunately, it won't help me in Kaggle as restarting rolls everything back.

And I still can't use my Kaggle [notebook](https://www.kaggle.com/code/vbmokin/pollen-bn-for-paper) on a different my dataset. I had to prepare the data in Python, save it in .csv, and then read it in the R notebook and build a Bayesian network there - everything works in R.

**Comment by erdogant** [comment]
I'm not sure whether this issue has solved itself, but I am closing it. Let me know if it remains an issue. Hopefully, time has fixed something. Otherwise, reopen again plz.
